steps:
  # Step 1: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-docker.pkg.dev/disco-beach-461517-m5/gcr.io/react-image:latest', # Tagging as 'react-image:latest' in the 'gcr.io' repository
      '.'
    ]

  # Step 2: Push the Docker Image to Google Artifact Registry

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-docker.pkg.dev/disco-beach-461517-m5/gcr.io/react-image:latest' # Pushing 'react-image:latest' to the 'gcr.io' repository
    ]

